# Generated by Django 3.2.25 on 2024-05-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0004_historicalperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='response_time',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Time taken to acknowledge POs in hours', max_digits=8, null=True),
        ),
    ]
