# Generated by Django 3.2.25 on 2024-05-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0005_purchaseorder_response_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='average_response_time',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average response time in hours', max_digits=8, null=True),
        ),
    ]
